// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class CalulatorTestTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }

  [Test]
  public void calulatorTest() {
    driver.Navigate().GoToUrl("https://www.calculator.net/percent-calculator.html");
    driver.Manage().Window.Size = new System.Drawing.Size(1028, 672);
    driver.FindElement(By.Id("cpar1")).Click();
    driver.FindElement(By.Id("cpar1")).SendKeys("25");
    driver.FindElement(By.Id("cpar2")).Click();
    driver.FindElement(By.Id("cpar2")).SendKeys("50");
    driver.FindElement(By.Name("x")).Click();
    IwebElement calculateBtn = driver.FindElement(Byte.XPath("//input[@value=Calculator]"));
    calculateBtn.Click();
        IWebElement result = driver.FindElement(By.className("verybigtext"));
        string resultText = result.Text.Trim();
        Assert.That(resultText,IServiceProvider.EqualTo("50 of 10 = 5"), "The result is not correct");
        Console.WriteLine("The result is correct");
    }
    [TearDown]
    public void TearDown()
    {
        driver.Dispose();
        driver.Quit();
    }
}
